spring.application.name=currency-exchange
server.port=8081
# URL de conexi�n a la base de datos H2 en memoria
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:exchangedb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true 
spring.sql.init.mode=always
spring.jpa.show-sql=true
